[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]

dependencies = [
    "sif-parser",
    "numpy",
    "scipy",
    "pillow",
    "sympy",
    "matplotlib>=3.8",
    "ipython",
    "sif-parser"
]

build-backend = "setuptools.build_meta"